#!/bin/bash

INSTALLER=/tmp/$USER-miniconda.sh

wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O $INSTALLER

# this is an install of python 2.7.15. Cannot yum install as broken. So a compiled version is here.
# if the old 2.6 default /usr/bin version is needed we need to alter this approach
#export PATH=/mnt/apps/Python/bin/:$PATH

sh $INSTALLER -b -p /shelf/apps/$USER/conda -f

rm $INSTALLER

echo "# folling 3 lines are for conda install. Auto done with install-bioconda" >> /storage/home/users/$USER/.bashrc
echo ". /shelf/apps/$USER/conda/etc/profile.d/conda.sh" >> /storage/home/users/$USER/.bashrc
echo "conda activate" >> /storage/home/users/$USER/.bashrc
echo "conda deactivate" >> /storage/home/users/$USER/.bashrc

# although conda complains about this, it is better to have this so it works through qsub
# otherwise you have to avtivate the conda envs and qsub with -V for it to work
echo "# conda. Force it to find it:" >> /storage/home/users/$USER/.bash_profile
echo "export PATH=/shelf/apps/$USER/conda/bin/:\$PATH" >> /storage/home/users/$USER/.bash_profile


source /storage/home/users/$USER/.bashrc

conda config --add channels R
conda config --add channels defaults
conda config --add channels conda-forge
conda config --add channels bioconda

#echo "INFO:
#echo "you will have to log out and back in again for this to work. "
#echo "Or run:" 
#echo "      source ~/.bashrc"
#echo "We strongly advise using envs: https://conda.io/docs/user-guide/tasks/manage-environments.html"
#echo "installing packages: https://bioconda.github.io/recipes.html"

